- README.md
- _config.yml
-   [ ] Enhancement (non-breaking change which enhances functionality)
-   [ ] I have read the **[README](./README.md)** document.
> New additions

- README.md
> Monthly additions

- README.md
> icon added

- README.md
-   [ ] Enhancement (non-breaking change which enhances functionality)
-   [x] Bug Fix (non-breaking change which fixes an issue).
> removed https://www.archives-online.org/ due to 404s

- README.md
- _layouts/default.html
> archives online and open eu data added

- README.md
> frauenarchiv added

- README.md
> Update Nov 2019

- README.md
- SECURITY.md
> Update Dec 2019

- .github/labeler.yml
- LICENSE.md
- README.md
-   [x] New feature (non-breaking change which adds functionality).
-   [x] Bug Fix (non-breaking change which fixes an issue).
-   [x] My change requires a change to the documentation.
-   [x] I have updated the documentation accordingly.
> Update Jan 2020

- README.md
-   [ ] Enhancement (non-breaking change which enhances functionality)
-   [ ] I have read the **[README](./README.md)** document.
> Update Mar 2020

- README.md
-   [x] My change requires a change to the documentation.
-   [x] I have updated the documentation accordingly.
> Update April 2020

- README.md
> Update May 2020

- README.md
-   [x] My change requires a change to the documentation.
-   [x] I have updated the documentation accordingly.
> Update jun 2020

- README.md
-   [x] My change requires a change to the documentation.
-   [x] I have updated the documentation accordingly.
> Update July 2020

- README.md
> Update Dec 2020

- README.md
- SLUB Dresden added
- UB Heidelberg added
- Digitale Sammlungen added
- ZLB added
- Archivportal added
- Deutsche Digitale Bibliothek added
- leobw added
- Bavarikon added
> Update mar 2021

- README.md
Added "LexM - Encyclopedia of musicians persecuted during the Nazi era" to Section "Germany"
LexM provides an extensive database of persecuted musicians, accompanied by sources and literature on each subject.
- [  ] Table of contents has been updated (if a section is added / removed).
> New addition: LexM - Encyclopedia of musicians persecuted during the Nazi era.

- README.md
> Update apr 2021

- .github/ISSUE_TEMPLATE/addition.md
- .github/ISSUE_TEMPLATE/edit.md
- .github/ISSUE_TEMPLATE/removal.md
- CONTRIBUTING.md
> issue templates

- README.md
- feat[README.md]: Schweizerisches Wirtschaftsarchiv added
> 2021 Dec Update

- README.md
> Update Jan 2022

- README.md
> Update Feb 2022

- README.md
> Update Mar 2022

- README.md
> Update apr 2022

- README.md
> Update May/June 2022

- README.md
This adds the National Records of Scotland which is similar to #44 for Scotland. It is exclusive to Scottish government. It differs from the NLS as this is for more government records and official stats.
> feat: Add National Records of Scotland

- README.md
> Update August September 2022

- README.md
Adds the national archives of the Netherlands for official national information.
> feat: Add Nationaal Archief

- README.md
Adds the archives and records from the United Nations. I popped this in Global as 193 countries are in the UN and that seems to be pretty global 😆
> feat: Add United Nations Archives to Global

- CITATION.cff
- README.md
- package.json
- pnpm-lock.yaml
> Add citation cff

- README.md
- [PICTURA paedagogica](https://pictura.bbf.dipf.de/viewer/index/) - Digital image archive on the history of education with 131'155 objects.
> fix: removal of non accessible or out of scope entries

- CITATION.cff
- src/lib/data/entries.json
Add transcriptiones
transcriptiones is a platform for sharing, accessing and editing transcriptions of manuscript sources (which are usually not available anywhere else).
> transcriptiones added

- src/lib/data/entries.json
Introduction to Digital History by @wissen-ist-acht added
Add / Remove / Change `{entry name}` in `src/lib/data/entries.json`.
Describe why this change is made. Alternatively, refer to existing issues if any. You could try to answer:
- Why do you find this resource awesome?
- How do you use this resource in your workflow?
- What advantages / disadvantages does it have compared to {another resource}?
Please ensure that you have completed the following tasks:
_Contributors, please ensure that_:
- A **short pitch** is included in the pull request description.
- The addition you proposed is NOT part of [everything that did not make it into the list](https://github.com/maehr/awesome-digital-history/wiki).
_Maintainers, please ensure that_:
- The above criteria are followed.
- …
> feat(entries.json): Introduction to Digital History added

- README.md
- src/lib/data/entries.json
Add `historicum.net` in `src/lib/data/entries.json`.
See issue #65 
Please ensure that you have completed the following tasks:
> New entry "historicum.net"
